# Generated by Django 4.1.5 on 2023-01-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_adress',
            new_name='billing_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_adress',
            new_name='shipping_address',
        ),
    ]
