# Generated by Django 4.1.5 on 2023-02-01 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_category_product_primary_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_products', to='cart.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_categories',
            field=models.ManyToManyField(blank=True, to='cart.category'),
        ),
    ]
